id: A8613D86B
title: Guru Yoga for Pacifying Spirits and Sickness of the Heart
type: translation
pechas:
- I78B82B1B
- I3B6D211D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:30.959126
  last_modified_at: 2023-01-04 12:12:30.959132
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I78B82B1B/F5CA: 87D3
  I3B6D211D/9E1C: 87D3
